#!/usr/bin/env python

import sys

def partitioning_function(key):
    return hash(key)

def partition(filenames):
    wps = []
    for f in filenames:
        wps.append(open(f, "wb"))
    n_reducers = len(filenames)
    for line in sys.stdin:
        [ key, val ] = line.split(None, 1)
        p = partitioning_function(key) % n_reducers
        wps[p].write(line)
    for wp in wps: wp.close()

def main():
    filenames = sys.argv[1:]
    sys.exit(partition(filenames))

main()
