#!/bin/bash

# convention. increase this number BEFORE you make a release
# (i.e., if VERSION=04, it means version 3.04 HAS BEEN released)
VERSION=05

# taura -> ttaauu

if [ ! $# -eq 1 ]; then
  echo "Usage: $0 YOUR_SOURCEFORGE_ACCOUNT"
  exit 1
fi

USER=$1
DIR=gxp-3.${VERSION}

cvs up
mkdir -p releases
cd releases
cvs -d :ext:${USER}@gxp.cvs.sourceforge.net:/cvsroot/gxp export -r HEAD gxp3
mv gxp3 ${DIR}
tar cvf ${DIR}.tar ${DIR}
bzip2 ${DIR}.tar
rsync -avP -e ssh ${DIR}.tar.bz2 ${USER}@frs.sourceforge.net:uploads/
cd ..

ls releases

cat <<EOF 
now login sourceforge from https://sourceforge.net/account/login.php
and https://sourceforge.net/project/admin/editreleases.php?package_id=282790&group_id=233088
(if you are lost, login goto Admin -> File Release)
EOF

