#!/bin/bash

# convention. increase this number BEFORE you make a release
# (i.e., if VERSION=04, it means version 3.04 HAS BEEN released)
VERSION=04

if [ ! $# -eq 1 ]; then
  echo "Usage: $0 YOUR_SOURCEFORGE_ACCOUNT"
  exit 1
fi

USER=$1
DIR=gxp-3.${VERSION}

cvs up
mkdir -p releases
cd releases
cvs -d :ext:${USER}@gxp.cvs.sourceforge.net:/cvsroot/gxp export -r HEAD gxp3
mv gxp3 ${DIR}
tar cvf ${DIR}.tar ${DIR}
bzip2 ${DIR}.tar
rsync -avP -e ssh ${DIR}.tar.bz2 ${USER}@frs.sourceforge.net:uploads/
cd ..

ls releases
