#!/usr/bin/env python
# Copyright (c) 2009 by Kenjiro Taura. All rights reserved.
# Copyright (c) 2008 by Kenjiro Taura. All rights reserved.
# Copyright (c) 2007 by Kenjiro Taura. All rights reserved.
# Copyright (c) 2006 by Kenjiro Taura. All rights reserved.
# Copyright (c) 2005 by Kenjiro Taura. All rights reserved.
#
# THIS MATERIAL IS PROVIDED AS IS, WITH ABSOLUTELY NO WARRANTY 
# EXPRESSED OR IMPLIED.  ANY USE IS AT YOUR OWN RISK.
# 
# Permission is hereby granted to use or copy this program
# for any purpose,  provided the above notices are retained on all 
# copies. Permission to modify the code and to distribute modified
# code is granted, provided the above notices are retained, and
# a notice that the code was modified is included with the above
# copyright notice.
#
# $Header: /cvsroot/gxp/gxp3/gxpbin/gifconfig,v 1.3 2010/03/05 05:27:09 ttaauu Exp $
# $Name:  $
#

import socket,string,sys

import ifconfig2

def Ws(s):
    sys.stdout.write(s)

def Es(s):
    sys.stderr.write(s)


def main():
    host = socket.gethostname()
    prio_str = ""
    if len(sys.argv) > 1:
        prio_str = sys.argv[1]
    prio,msg = ifconfig2.compile_prio(prio_str)
    if prio is None:
        Es("%s: %s\n" % (host, msg))
        return 1
    addrs = ifconfig2.get_my_addrs(prio)
    Ws("%s: %s\n" % (host, string.join(addrs, " ")))

if __name__ == "__main__":
    sys.exit(main())

# $Log: gifconfig,v $
# Revision 1.3  2010/03/05 05:27:09  ttaauu
# stop extending PYTHONPATH. see 2010-3-5 ChangeLog
#
# Revision 1.2  2009/06/06 14:06:26  ttaauu
# added headers and logs
#
